server:
  port: '9991'
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
spring:
  application:
    name: demo-factory-server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
#        one-indexed-parameters: true #1페이지부터 시작하지만 부가정보들과 맞지 않는다. 이를 감안하면 쓸수 있다.
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
#        show_sql: false
#        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: demofactory
    username: demofactory
    url: jdbc:mariadb://localhost:6281/demofactory
logging:
#  file:
#    path: log
#    name: log/digitaltwin.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: log/digitaltwin.%d{yyyy-MM-dd}-%i.log
#      max-file-size: 10MB
  level:
    p6spy: warn
    root: info
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
  pattern:
    dateformat: Asia/Seoul
com:
  demofactory:
    logo-upload-path: C:/file/demofactory/upload/factory
    logo-file-name: logo.png
    model-upload-path: C:/file/demofactory/upload/factory
    stomp:
      endpoint: /ws
      destination-prefixes: /app
      factory: /dt/factory
management:
  endpoints:
    web:
      exposure:
        include: beans,health,metrics
      path-mapping:
        health: healthcheck
      base-path: /manage
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
    metrics:
      enabled: true
